<HomeScreen>:
    MDBoxLayout:
        orientation: "vertical"
        spacing: '20sp'

        MDTopAppBar:
            title: "Weather"
        MDBoxLayout:
            MDTextField:
                hint_text: "Місто"
                mode: "fill"
            MDIconButton:
                icon: "magnify"
                md_bg_color: 'purple'
                icon_size: "64sp"
            